# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    # - task: DockerCompose@0
    #   displayName: Build services
    #   inputs:
    #     containerregistrytype: 'Azure Container Registry'
    #     azureSubscription: 'Hexagon MI Nexus - sbx(6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5)'
    #     azureContainerRegistry: '{"loginServer":"nexuspocchatbot.azurecr.io", "id" : "/subscriptions/6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5/resourceGroups/nexus-sbx-chatbot/providers/Microsoft.ContainerRegistry/registries/nexusPocChatbot"}'

    #     dockerComposeFile: '$(Build.SourcesDirectory)/docker/docker-compose.yaml'
    #     additionalDockerComposeFiles: '$(Build.SourcesDirectory)/docker/docker-compose.middleware.yaml'
    #     action: 'Run a Docker Compose command'
    #     dockerComposeCommand: 'up --build --no-start'

    # - task: DockerCompose@0
    #   displayName: Push services
    #   inputs:
    #     containerregistrytype: 'Azure Container Registry'
    #     azureSubscription: 'Hexagon MI Nexus - sbx(6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5)'
    #     azureContainerRegistry: '{"loginServer":"nexuspocchatbot.azurecr.io", "id" : "/subscriptions/6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5/resourceGroups/nexus-sbx-chatbot/providers/Microsoft.ContainerRegistry/registries/nexusPocChatbot"}'
    #     dockerComposeFile: '$(Build.SourcesDirectory)/docker/docker-compose.yml'
    #     action: 'Push services'
    #     acrName: 'nexusPocChatbot'
    #     acrUsername: 'nexusPocChatbot'
    #     acrPassword: 'ThHs0At2kekBPhyR8UI4L0e99xamSKLGBntRapFXyJ+ACRCf+JpN'
  
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Hexagon MI Nexus - sbx(6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5)'
        appName: 'nexussbxchatbot'
        appSettings:
          -DOCKER_REGISTRY_SERVER_USERNAME nexussbxchatbot
          -DOCKER_REGISTRY_SERVER_URL nexussbxchatbot.azurecr.io
          -DOCKER_REGISTRY_SERVER_PASSWORD f/gmMXOZxkf8DvURypLk0VAZyO7Wbi5yoCRmslKUB0+ACRC5eWhk
        multicontainerConfigFile: '$(Build.SourcesDirectory)/docker/docker-compose.middleware.yml'

    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: 'Hexagon MI Nexus - sbx(6d1a72c8-14d3-4453-b9c0-fc3bbd6c82d5)'
        appName: 'nexussbxchatbot'
        appSettings:
          -DOCKER_REGISTRY_SERVER_USERNAME nexussbxchatbot
          -DOCKER_REGISTRY_SERVER_URL nexussbxchatbot.azurecr.io
          -DOCKER_REGISTRY_SERVER_PASSWORD f/gmMXOZxkf8DvURypLk0VAZyO7Wbi5yoCRmslKUB0+ACRC5eWhk
        multicontainerConfigFile: '$(Build.SourcesDirectory)/docker/docker-compose.yml'