apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: nginx
    spec:
      containers:
        - image: nexussbxchatbot.azurecr.io/chatbot/nginx
          name: nginx
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx
            - mountPath: /etc/nginx/proxy.conf
              name: nginx-proxy
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
      restartPolicy: Always
      volumes:
        - name: nginx
          persistentVolumeClaim:
            claimName: nginx
        - name: nginx-proxy
          persistentVolumeClaim:
            claimName: nginx-proxy
        - name: nginx-conf
          persistentVolumeClaim:
            claimName: nginx-conf
status: {}
